[mypy]
python_version = 3.12
warn_unused_configs = True
disable_error_code = import-untyped

[mypy-setuptools.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True
